import { db, categoriesTable, restaurantsTable, menuItemsTable } from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  const existingCategories = await db.select().from(categoriesTable);
  if (existingCategories.length > 0) {
    console.log("Database already seeded, skipping.");
    process.exit(0);
  }

  const categories = await db.insert(categoriesTable).values([
    { name: "Khmer Food", icon: "🍲", slug: "khmer" },
    { name: "Fast Food", icon: "🍔", slug: "fast-food" },
    { name: "Noodles", icon: "🍜", slug: "noodles" },
    { name: "Seafood", icon: "🦞", slug: "seafood" },
    { name: "Desserts", icon: "🍡", slug: "desserts" },
    { name: "Drinks", icon: "🥤", slug: "drinks" },
    { name: "BBQ", icon: "🍖", slug: "bbq" },
    { name: "Vegetarian", icon: "🥗", slug: "vegetarian" },
  ]).returning();

  console.log(`Inserted ${categories.length} categories`);

  const restaurants = await db.insert(restaurantsTable).values([
    {
      name: "Khmer Kitchen",
      description: "Authentic Cambodian cuisine with traditional recipes passed down through generations",
      imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600",
      rating: 4.8,
      reviewCount: 342,
      deliveryTime: "20-30 min",
      minimumOrder: 5,
      categoryId: categories[0].id,
      categoryName: "Khmer Food",
      address: "Street 51, Phnom Penh",
      isOpen: true,
      isFeatured: true,
    },
    {
      name: "BFC Burger House",
      description: "Juicy gourmet burgers, crispy fries and refreshing shakes delivered hot to your door",
      imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600",
      rating: 4.6,
      reviewCount: 218,
      deliveryTime: "15-25 min",
      minimumOrder: 3,
      categoryId: categories[1].id,
      categoryName: "Fast Food",
      address: "Street 63, Phnom Penh",
      isOpen: true,
      isFeatured: true,
    },
    {
      name: "Noodle Palace",
      description: "Fresh handmade noodles with rich broths and toppings — Cambodia's noodle heaven",
      imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600",
      rating: 4.7,
      reviewCount: 189,
      deliveryTime: "25-35 min",
      minimumOrder: 4,
      categoryId: categories[2].id,
      categoryName: "Noodles",
      address: "Toul Tom Poung, Phnom Penh",
      isOpen: true,
      isFeatured: true,
    },
    {
      name: "Mekong Seafood",
      description: "Fresh seafood straight from the Mekong River, grilled or steamed your way",
      imageUrl: "https://images.unsplash.com/photo-1534482421-64566f976cfa?w=600",
      rating: 4.5,
      reviewCount: 156,
      deliveryTime: "30-40 min",
      minimumOrder: 8,
      categoryId: categories[3].id,
      categoryName: "Seafood",
      address: "Riverside, Phnom Penh",
      isOpen: true,
      isFeatured: true,
    },
    {
      name: "Sweet Treats Cambodia",
      description: "Traditional Cambodian sweets, desserts and snacks made fresh daily",
      imageUrl: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600",
      rating: 4.9,
      reviewCount: 412,
      deliveryTime: "20-30 min",
      minimumOrder: 2,
      categoryId: categories[4].id,
      categoryName: "Desserts",
      address: "BKK1, Phnom Penh",
      isOpen: true,
      isFeatured: false,
    },
    {
      name: "Tiger BBQ",
      description: "Charcoal BBQ meats, ribs and skewers with special house sauces",
      imageUrl: "https://images.unsplash.com/photo-1544025162-d76prerender694-bcaa-96c2b3fbc3c?w=600",
      rating: 4.4,
      reviewCount: 127,
      deliveryTime: "35-45 min",
      minimumOrder: 10,
      categoryId: categories[6].id,
      categoryName: "BBQ",
      address: "Chamkarmon, Phnom Penh",
      isOpen: true,
      isFeatured: false,
    },
    {
      name: "Green Bowl",
      description: "Fresh salads, veggie bowls and plant-based meals for health-conscious foodies",
      imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
      rating: 4.6,
      reviewCount: 98,
      deliveryTime: "20-25 min",
      minimumOrder: 4,
      categoryId: categories[7].id,
      categoryName: "Vegetarian",
      address: "Daun Penh, Phnom Penh",
      isOpen: true,
      isFeatured: false,
    },
    {
      name: "Pho & Beyond",
      description: "Vietnamese-inspired pho and noodle soups with rich broths simmered for 12 hours",
      imageUrl: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600",
      rating: 4.7,
      reviewCount: 203,
      deliveryTime: "25-35 min",
      minimumOrder: 5,
      categoryId: categories[2].id,
      categoryName: "Noodles",
      address: "Sen Sok, Phnom Penh",
      isOpen: true,
      isFeatured: false,
    },
  ]).returning();

  console.log(`Inserted ${restaurants.length} restaurants`);

  const menuItems = await db.insert(menuItemsTable).values([
    // Khmer Kitchen
    {
      restaurantId: restaurants[0].id,
      name: "Amok Fish",
      description: "Traditional Cambodian fish curry steamed in banana leaf with coconut cream",
      price: 6.50,
      imageUrl: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=400",
      category: "Main Dishes",
      isAvailable: true,
      isPopular: true,
    },
    {
      restaurantId: restaurants[0].id,
      name: "Lok Lak",
      description: "Stir-fried beef with lime dipping sauce and fried egg on rice",
      price: 7.00,
      imageUrl: "https://images.unsplash.com/photo-1598514983318-2f64f8f4796c?w=400",
      category: "Main Dishes",
      isAvailable: true,
      isPopular: true,
    },
    {
      restaurantId: restaurants[0].id,
      name: "Khmer Soup",
      description: "Traditional sour soup with vegetables and herbs",
      price: 4.50,
      imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400",
      category: "Soups",
      isAvailable: true,
      isPopular: false,
    },
    {
      restaurantId: restaurants[0].id,
      name: "Sticky Rice with Mango",
      description: "Sweet glutinous rice served with fresh mango slices and coconut cream",
      price: 3.00,
      imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400",
      category: "Desserts",
      isAvailable: true,
      isPopular: false,
    },
    // BFC Burger House
    {
      restaurantId: restaurants[1].id,
      name: "BFC Classic Burger",
      description: "Signature beef patty with special BFC sauce, lettuce, tomato and pickles",
      price: 5.50,
      imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
      category: "Burgers",
      isAvailable: true,
      isPopular: true,
    },
    {
      restaurantId: restaurants[1].id,
      name: "Double Cheese Stack",
      description: "Two beef patties with double cheese, caramelized onion and smoky bacon",
      price: 7.50,
      imageUrl: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400",
      category: "Burgers",
      isAvailable: true,
      isPopular: true,
    },
    {
      restaurantId: restaurants[1].id,
      name: "Crispy Chicken Sandwich",
      description: "Crispy fried chicken breast with coleslaw and honey mustard",
      price: 6.00,
      imageUrl: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400",
      category: "Sandwiches",
      isAvailable: true,
      isPopular: false,
    },
    {
      restaurantId: restaurants[1].id,
      name: "Loaded Fries",
      description: "Crispy fries topped with cheese sauce, bacon bits and chives",
      price: 3.50,
      imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400",
      category: "Sides",
      isAvailable: true,
      isPopular: false,
    },
    // Noodle Palace
    {
      restaurantId: restaurants[2].id,
      name: "Beef Pho",
      description: "Rich beef bone broth with rice noodles, tender beef slices and fresh herbs",
      price: 5.50,
      imageUrl: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=400",
      category: "Noodle Soups",
      isAvailable: true,
      isPopular: true,
    },
    {
      restaurantId: restaurants[2].id,
      name: "Pad Thai",
      description: "Stir-fried rice noodles with egg, bean sprouts, peanuts and lime",
      price: 5.00,
      imageUrl: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400",
      category: "Stir-Fried Noodles",
      isAvailable: true,
      isPopular: true,
    },
    {
      restaurantId: restaurants[2].id,
      name: "Num Banh Chok",
      description: "Traditional Khmer rice noodles with green fish curry and fresh vegetables",
      price: 4.50,
      imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400",
      category: "Noodle Soups",
      isAvailable: true,
      isPopular: false,
    },
    // Mekong Seafood
    {
      restaurantId: restaurants[3].id,
      name: "Grilled Tiger Prawns",
      description: "Fresh tiger prawns grilled with garlic butter and lemon sauce",
      price: 12.00,
      imageUrl: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=400",
      category: "Grilled",
      isAvailable: true,
      isPopular: true,
    },
    {
      restaurantId: restaurants[3].id,
      name: "Steamed Whole Fish",
      description: "Fresh river fish steamed with ginger, spring onion and soy sauce",
      price: 14.00,
      imageUrl: "https://images.unsplash.com/photo-1534482421-64566f976cfa?w=400",
      category: "Steamed",
      isAvailable: true,
      isPopular: false,
    },
    // Sweet Treats
    {
      restaurantId: restaurants[4].id,
      name: "Nom Krok",
      description: "Traditional coconut rice cakes with pandan and sweet fillings",
      price: 2.50,
      imageUrl: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400",
      category: "Traditional Sweets",
      isAvailable: true,
      isPopular: true,
    },
    {
      restaurantId: restaurants[4].id,
      name: "Mango Sticky Rice",
      description: "Sweet glutinous rice with ripe mango and coconut milk drizzle",
      price: 3.50,
      imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400",
      category: "Traditional Sweets",
      isAvailable: true,
      isPopular: true,
    },
    // Green Bowl
    {
      restaurantId: restaurants[6].id,
      name: "Garden Power Bowl",
      description: "Quinoa, roasted veggies, avocado, chickpeas and tahini dressing",
      price: 6.50,
      imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
      category: "Bowls",
      isAvailable: true,
      isPopular: true,
    },
    {
      restaurantId: restaurants[6].id,
      name: "Fresh Mango Salad",
      description: "Green mango, peanuts, dried shrimp with tangy lime dressing",
      price: 5.00,
      imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
      category: "Salads",
      isAvailable: true,
      isPopular: false,
    },
    // Pho & Beyond
    {
      restaurantId: restaurants[7].id,
      name: "Special Pho",
      description: "12-hour bone broth pho with rare beef, brisket, tripe and meatballs",
      price: 7.00,
      imageUrl: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=400",
      category: "Pho",
      isAvailable: true,
      isPopular: true,
    },
    {
      restaurantId: restaurants[7].id,
      name: "Bun Bo Hue",
      description: "Spicy lemongrass beef noodle soup with pork and fresh herbs",
      price: 6.50,
      imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400",
      category: "Spicy Noodles",
      isAvailable: true,
      isPopular: true,
    },
  ]).returning();

  console.log(`Inserted ${menuItems.length} menu items`);
  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
